with open('src/components/resume-builder/InlineEditor.tsx', 'r', encoding='utf-8') as f:
    lines = f.readlines()

keep_before = lines[:408]
keep_after = lines[433:]

new_middle = [
    '\n',
    '        {/* AI toggle */}\n',
    '        <button\n',
    '          onMouseDown={e => { e.preventDefault(); setShowAiPanel(s => !s); setShowStylePanel(false); }}\n',
    "          className={`flex items-center gap-1 px-2 py-1 rounded-lg text-[10px] font-bold transition-all ${showAiPanel ? 'bg-purple-500/30 text-purple-200' : 'text-purple-300 hover:bg-white/10'}`}\n",
    '        >\n',
    '          <Wand2 className="w-3 h-3" />\n',
    '          AI\n',
    '        </button>\n',
    '\n',
    '        <div className="flex-1" />\n',
    '\n',
    '        <button\n',
    '          onMouseDown={e => { e.preventDefault(); onCommit(); }}\n',
    '          className="flex items-center gap-1 px-3 py-1.5 rounded-lg text-[10px] font-black text-white transition-all"\n',
    '          style={{ background: "linear-gradient(135deg, #6366f1, #8b5cf6)" }}\n',
    '        >\n',
    '          <Check className="w-3.5 h-3.5" /> Save\n',
    '        </button>\n',
    '      </div>\n',
    '\n',
    '      {/* AI Panel */}\n',
    '      {showAiPanel && (\n',
    '        <div className="px-3 pb-3 space-y-2.5" style={{ borderTop: "1px solid rgba(255,255,255,0.08)", paddingTop: "10px" }}>\n',
    '          <p className="text-[9px] font-black text-white/40 uppercase tracking-widest mb-2">AI Enhance</p>\n',
    '          <div className="flex flex-wrap gap-1.5">\n',
    '            {AI_TAGS.map(tag => (\n',
    '              <button\n',
    '                key={tag.id}\n',
    '                onMouseDown={e => {\n',
    '                  e.preventDefault();\n',
    '                  setSelectedTags(prev => prev.includes(tag.id) ? prev.filter(t => t !== tag.id) : [...prev, tag.id]);\n',
    '                }}\n',
    '                className="flex items-center gap-1 px-2 py-1 rounded-full text-[10px] font-bold transition-all"\n',
    '                style={{\n',
    "                  background: selectedTags.includes(tag.id) ? 'rgba(139,92,246,0.4)' : 'rgba(255,255,255,0.08)',\n",
    "                  border: selectedTags.includes(tag.id) ? '1px solid rgba(139,92,246,0.6)' : '1px solid rgba(255,255,255,0.1)',\n",
    "                  color: selectedTags.includes(tag.id) ? '#c4b5fd' : 'rgba(255,255,255,0.6)',\n",
    '                }}\n',
    '              >\n',
    '                <span>{tag.icon}</span> {tag.label}\n',
    '              </button>\n',
    '            ))}\n',
    '          </div>\n',
    '          {contextTags.length > 0 && (\n',
    '            <div>\n',
    '              <p className="text-[8px] text-white/30 uppercase tracking-widest mb-1">Resume context</p>\n',
    '              <div className="flex flex-wrap gap-1">\n',
    '                {contextTags.slice(0, 5).map((tag, i) => (\n',
    '                  <span key={i} className="px-2 py-0.5 rounded-full text-[9px] font-medium" style={{ background: "rgba(99,102,241,0.15)", color: "rgba(165,180,252,0.8)", border: "1px solid rgba(99,102,241,0.2)" }}>\n',
    '                    {tag}\n',
    '                  </span>\n',
    '                ))}\n',
    '              </div>\n',
    '            </div>\n',
    '          )}\n',
    '          <input\n',
    '            type="text"\n',
    '            placeholder="Custom instruction..."\n',
    '            value={customInstruction}\n',
    '            onChange={e => setCustomInstruction(e.target.value)}\n',
    '            onKeyDown={e => { if (e.key === "Enter") { e.preventDefault(); enhanceWithAI(); } }}\n',
    '            className="w-full px-2.5 py-1.5 rounded-lg text-[11px] focus:outline-none focus:ring-1 focus:ring-purple-500"\n',
    '            style={{ background: "rgba(255,255,255,0.08)", border: "1px solid rgba(255,255,255,0.12)", color: "rgba(255,255,255,0.8)" }}\n',
    '          />\n',
    '          <button\n',
    '            onMouseDown={e => { e.preventDefault(); enhanceWithAI(); }}\n',
    '            disabled={aiLoading}\n',
    '            className="w-full flex items-center justify-center gap-2 py-2 rounded-xl text-[11px] font-black text-white transition-all disabled:opacity-50"\n',
    '            style={{ background: "linear-gradient(135deg, #7c3aed, #a855f7)" }}\n',
    '          >\n',
    '            {aiLoading ? <Loader2 className="w-3.5 h-3.5 animate-spin" /> : <Wand2 className="w-3.5 h-3.5" />}\n',
    "            {aiLoading ? 'Generating...' : 'Generate with AI'}\n",
    '          </button>\n',
    '          {aiError && (\n',
    '            <div className="flex items-start gap-2 px-2 py-1.5 rounded-lg" style={{ background: "rgba(239,68,68,0.1)", border: "1px solid rgba(239,68,68,0.2)" }}>\n',
    '              <span className="text-[10px] text-red-400 flex-1">{aiError}</span>\n',
    '              <button onMouseDown={e => { e.preventDefault(); setAiError(""); }} className="text-red-400/60 hover:text-red-400 shrink-0"><X className="w-3 h-3" /></button>\n',
    '            </div>\n',
    '          )}\n',
    '          {aiPreview && (\n',
    '            <div className="rounded-xl overflow-hidden" style={{ border: "1px solid rgba(139,92,246,0.3)", background: "rgba(139,92,246,0.08)" }}>\n',
    '              <div className="px-3 py-2">\n',
    '                <p className="text-[9px] font-black text-purple-400 uppercase tracking-widest mb-1.5">Suggestion</p>\n',
    '                <p className="text-[11px] leading-relaxed text-white/80">{aiPreview}</p>\n',
    '              </div>\n',
    '              <div className="flex gap-1.5 px-3 pb-2.5">\n',
    "                <button onMouseDown={e => { e.preventDefault(); if (aiPreview && !aiPreview.startsWith('Error:')) { onChange(aiPreview); setAiPreview(''); setShowAiPanel(false); } }} className=\"flex items-center gap-1 px-3 py-1.5 rounded-lg text-[10px] font-black text-white\" style={{ background: '#10b981' }}><Check className=\"w-3 h-3\" /> Apply</button>\n",
    '                <button onMouseDown={e => { e.preventDefault(); enhanceWithAI(); }} className="p-1.5 rounded-lg text-white/40 hover:text-white/70 hover:bg-white/10"><RefreshCw className="w-3 h-3" /></button>\n',
    '                <button onMouseDown={e => { e.preventDefault(); setAiPreview(""); }} className="p-1.5 rounded-lg text-white/40 hover:text-white/70 hover:bg-white/10"><X className="w-3 h-3" /></button>\n',
    '              </div>\n',
    '            </div>\n',
    '          )}\n',
    '        </div>\n',
    '      )}\n',
    '\n',
]

result = keep_before + new_middle + keep_after

with open('src/components/resume-builder/InlineEditor.tsx', 'w', encoding='utf-8') as f:
    f.writelines(result)

print('Done:', len(result), 'lines')
