export interface DesignTemplate {
  id: string;
  name: string;
  description: string;
  preview: {
    primaryColor: string;
    secondaryColor: string;
    accentColor: string;
    fontFamily: string;
    layout: 'sidebar-left' | 'sidebar-right' | 'single' | 'modern-header' | 'double-header';
    backgroundColor: string;
    textColor: string;
  };
  design: {
    fontSize: number;
    lineHeight: number;
    marginLR: number;
    marginTB: number;
    entrySpacing: number;
    sectionSpacing: number;
    headingStyle: string;
    headingCapitalization: 'uppercase' | 'none';
    headingSize: 's' | 'm' | 'l';
    nameSize: 's' | 'm' | 'l';
    nameBold: boolean;
    titleSize: 's' | 'm' | 'l';
    titleStyle: 'normal' | 'italic';
    titlePosition: 'below' | 'beside';
    personalAlign: 'left' | 'center' | 'right';
    personalArrangement: 'default' | 'horizontal' | 'stacked';
    personalIconShow: boolean;
    personalBulletShow: boolean;
    personalBarShow: boolean;
    personalIconStyle: 'default' | 'minimal' | 'icon-only';
    photoShow: boolean;
    photoGrayscale: boolean;
    photoSize: 's' | 'm' | 'l';
    photoShape: 'circle' | 'square' | 'rounded';
    skillsStyle: 'grid' | 'list' | 'compact' | 'bubble' | 'level';
    skillsColumns: number;
    languagesStyle: 'grid' | 'list' | 'compact' | 'bubble' | 'level';
    languagesColumns: number;
    interestsStyle: 'grid' | 'list' | 'compact' | 'bubble';
    interestsColumns: number;
    certificationsStyle: 'grid' | 'list' | 'compact' | 'bubble';
    certificationsColumns: number;
    showSummaryHeading: boolean;
    showPageNumbers: boolean;
    showEmailInFooter: boolean;
    showNameInFooter: boolean;
    linkUnderline: boolean;
    linkBlueColor: boolean;
    linkIcon: boolean;
    entryLayout: 'default' | 'compact' | 'detailed';
    entryTitleSize: 's' | 'm' | 'l';
    entrySubtitleStyle: 'normal' | 'italic';
    entrySubtitlePlacement: 'next-line' | 'same-line';
    descriptionIndent: boolean;
    listStyle: 'bullet' | 'dash' | 'number' | 'none';
    educationOrder: 'degree-school' | 'school-degree';
    workOrder: 'title-employer' | 'employer-title';
    workGroupPromotions: boolean;
    accentType: 'basic' | 'gradient' | 'outline';
    applyAccentTo: Array<'headings' | 'headingLine' | 'name' | 'photo' | 'sections'>;
  };
}

export const DESIGN_TEMPLATES: DesignTemplate[] = [
  {
    id: 'professional-purple',
    name: 'Professional Purple',
    description: 'Classic purple theme perfect for corporate positions',
    preview: {
      primaryColor: '#7c3aed',
      secondaryColor: '#f5f3ff',
      accentColor: '#5b21b6',
      fontFamily: 'Inter',
      layout: 'sidebar-left',
      backgroundColor: '#ffffff',
      textColor: '#1f2937',
    },
    design: {
      fontSize: 10.5,
      lineHeight: 1.45,
      marginLR: 12,
      marginTB: 16,
      entrySpacing: 8,
      sectionSpacing: 16,
      headingStyle: 'underline',
      headingCapitalization: 'uppercase',
      headingSize: 'm',
      nameSize: 'm',
      nameBold: true,
      titleSize: 'm',
      titleStyle: 'normal',
      titlePosition: 'below',
      personalAlign: 'left',
      personalArrangement: 'default',
      personalIconShow: true,
      personalBulletShow: false,
      personalBarShow: false,
      personalIconStyle: 'default',
      photoShow: false,
      photoGrayscale: false,
      photoSize: 'm',
      photoShape: 'circle',
      skillsStyle: 'grid',
      skillsColumns: 1,
      languagesStyle: 'grid',
      languagesColumns: 1,
      interestsStyle: 'grid',
      interestsColumns: 1,
      certificationsStyle: 'grid',
      certificationsColumns: 1,
      showSummaryHeading: true,
      showPageNumbers: true,
      showEmailInFooter: false,
      showNameInFooter: false,
      linkUnderline: true,
      linkBlueColor: false,
      linkIcon: true,
      entryLayout: 'default',
      entryTitleSize: 'm',
      entrySubtitleStyle: 'normal',
      entrySubtitlePlacement: 'next-line',
      descriptionIndent: false,
      listStyle: 'bullet',
      educationOrder: 'degree-school',
      workOrder: 'title-employer',
      workGroupPromotions: false,
      accentType: 'basic',
      applyAccentTo: ['headings', 'headingLine'],
    },
  },
  {
    id: 'modern-pink',
    name: 'Modern Pink',
    description: 'Fresh pink accent for creative professionals',
    preview: {
      primaryColor: '#ff4d7d',
      secondaryColor: '#fff1f2',
      accentColor: '#be185d',
      fontFamily: 'Outfit',
      layout: 'single',
      backgroundColor: '#ffffff',
      textColor: '#1f2937',
    },
    design: {
      fontSize: 10.5,
      lineHeight: 1.5,
      marginLR: 15,
      marginTB: 18,
      entrySpacing: 6,
      sectionSpacing: 14,
      headingStyle: 'underline',
      headingCapitalization: 'uppercase',
      headingSize: 'm',
      nameSize: 'l',
      nameBold: true,
      titleSize: 's',
      titleStyle: 'italic',
      titlePosition: 'below',
      personalAlign: 'center',
      personalArrangement: 'horizontal',
      personalIconShow: false,
      personalBulletShow: true,
      personalBarShow: false,
      personalIconStyle: 'default',
      photoShow: false,
      photoGrayscale: false,
      photoSize: 'm',
      photoShape: 'circle',
      skillsStyle: 'bubble',
      skillsColumns: 4,
      languagesStyle: 'grid',
      languagesColumns: 2,
      interestsStyle: 'grid',
      interestsColumns: 3,
      certificationsStyle: 'grid',
      certificationsColumns: 2,
      showSummaryHeading: true,
      showPageNumbers: false,
      showEmailInFooter: false,
      showNameInFooter: false,
      linkUnderline: false,
      linkBlueColor: false,
      linkIcon: true,
      entryLayout: 'default',
      entryTitleSize: 'm',
      entrySubtitleStyle: 'italic',
      entrySubtitlePlacement: 'next-line',
      descriptionIndent: false,
      listStyle: 'bullet',
      educationOrder: 'degree-school',
      workOrder: 'title-employer',
      workGroupPromotions: false,
      accentType: 'basic',
      applyAccentTo: ['headings', 'name'],
    },
  },
  {
    id: 'executive-blue',
    name: 'Executive Blue',
    description: 'Professional blue for senior leadership roles',
    preview: {
      primaryColor: '#1e40af',
      secondaryColor: '#eff6ff',
      accentColor: '#1d4ed8',
      fontFamily: 'Merriweather',
      layout: 'sidebar-left',
      backgroundColor: '#ffffff',
      textColor: '#1e3a8a',
    },
    design: {
      fontSize: 10,
      lineHeight: 1.5,
      marginLR: 14,
      marginTB: 18,
      entrySpacing: 10,
      sectionSpacing: 18,
      headingStyle: 'underline',
      headingCapitalization: 'uppercase',
      headingSize: 'm',
      nameSize: 'l',
      nameBold: true,
      titleSize: 'm',
      titleStyle: 'normal',
      titlePosition: 'below',
      personalAlign: 'left',
      personalArrangement: 'default',
      personalIconShow: true,
      personalBulletShow: false,
      personalBarShow: false,
      personalIconStyle: 'default',
      photoShow: false,
      photoGrayscale: false,
      photoSize: 'm',
      photoShape: 'square',
      skillsStyle: 'list',
      skillsColumns: 1,
      languagesStyle: 'grid',
      languagesColumns: 2,
      interestsStyle: 'grid',
      interestsColumns: 2,
      certificationsStyle: 'grid',
      certificationsColumns: 2,
      showSummaryHeading: true,
      showPageNumbers: true,
      showEmailInFooter: true,
      showNameInFooter: true,
      linkUnderline: true,
      linkBlueColor: true,
      linkIcon: false,
      entryLayout: 'detailed',
      entryTitleSize: 'm',
      entrySubtitleStyle: 'normal',
      entrySubtitlePlacement: 'next-line',
      descriptionIndent: true,
      listStyle: 'bullet',
      educationOrder: 'degree-school',
      workOrder: 'title-employer',
      workGroupPromotions: true,
      accentType: 'basic',
      applyAccentTo: ['headings', 'headingLine'],
    },
  },
  {
    id: 'minimal-dark',
    name: 'Minimal Dark',
    description: 'Elegant minimal design with dark accents',
    preview: {
      primaryColor: '#18181b',
      secondaryColor: '#fafafa',
      accentColor: '#27272a',
      fontFamily: 'Inter',
      layout: 'single',
      backgroundColor: '#ffffff',
      textColor: '#18181b',
    },
    design: {
      fontSize: 11,
      lineHeight: 1.6,
      marginLR: 18,
      marginTB: 20,
      entrySpacing: 5,
      sectionSpacing: 12,
      headingStyle: 'none',
      headingCapitalization: 'none',
      headingSize: 's',
      nameSize: 'l',
      nameBold: true,
      titleSize: 's',
      titleStyle: 'normal',
      titlePosition: 'below',
      personalAlign: 'left',
      personalArrangement: 'horizontal',
      personalIconShow: false,
      personalBulletShow: true,
      personalBarShow: false,
      personalIconStyle: 'default',
      photoShow: false,
      photoGrayscale: false,
      photoSize: 'm',
      photoShape: 'rounded',
      skillsStyle: 'compact',
      skillsColumns: 3,
      languagesStyle: 'compact',
      languagesColumns: 2,
      interestsStyle: 'compact',
      interestsColumns: 3,
      certificationsStyle: 'compact',
      certificationsColumns: 2,
      showSummaryHeading: false,
      showPageNumbers: false,
      showEmailInFooter: false,
      showNameInFooter: false,
      linkUnderline: true,
      linkBlueColor: true,
      linkIcon: false,
      entryLayout: 'compact',
      entryTitleSize: 's',
      entrySubtitleStyle: 'normal',
      entrySubtitlePlacement: 'next-line',
      descriptionIndent: false,
      listStyle: 'none',
      educationOrder: 'degree-school',
      workOrder: 'title-employer',
      workGroupPromotions: false,
      accentType: 'outline',
      applyAccentTo: ['name'],
    },
  },
  {
    id: 'creative-gradient',
    name: 'Creative Gradient',
    description: 'Vibrant gradient design for creative roles',
    preview: {
      primaryColor: '#8b5cf6',
      secondaryColor: '#faf5ff',
      accentColor: '#7c3aed',
      fontFamily: 'Poppins',
      layout: 'modern-header',
      backgroundColor: '#ffffff',
      textColor: '#1f2937',
    },
    design: {
      fontSize: 10.5,
      lineHeight: 1.45,
      marginLR: 12,
      marginTB: 16,
      entrySpacing: 8,
      sectionSpacing: 16,
      headingStyle: 'dot',
      headingCapitalization: 'uppercase',
      headingSize: 'm',
      nameSize: 'l',
      nameBold: true,
      titleSize: 'm',
      titleStyle: 'normal',
      titlePosition: 'below',
      personalAlign: 'center',
      personalArrangement: 'default',
      personalIconShow: true,
      personalBulletShow: false,
      personalBarShow: false,
      personalIconStyle: 'minimal',
      photoShow: false,
      photoGrayscale: false,
      photoSize: 'm',
      photoShape: 'circle',
      skillsStyle: 'level',
      skillsColumns: 2,
      languagesStyle: 'grid',
      languagesColumns: 2,
      interestsStyle: 'bubble',
      interestsColumns: 3,
      certificationsStyle: 'grid',
      certificationsColumns: 2,
      showSummaryHeading: true,
      showPageNumbers: false,
      showEmailInFooter: false,
      showNameInFooter: false,
      linkUnderline: false,
      linkBlueColor: false,
      linkIcon: true,
      entryLayout: 'default',
      entryTitleSize: 'm',
      entrySubtitleStyle: 'italic',
      entrySubtitlePlacement: 'next-line',
      descriptionIndent: false,
      listStyle: 'bullet',
      educationOrder: 'degree-school',
      workOrder: 'title-employer',
      workGroupPromotions: false,
      accentType: 'gradient',
      applyAccentTo: ['headings', 'name', 'sections'],
    },
  },
  {
    id: 'elegant-gold',
    name: 'Elegant Gold',
    description: 'Sophisticated design with gold accents',
    preview: {
      primaryColor: '#b45309',
      secondaryColor: '#fffbeb',
      accentColor: '#d97706',
      fontFamily: 'Playfair Display',
      layout: 'sidebar-right',
      backgroundColor: '#ffffff',
      textColor: '#1c1917',
    },
    design: {
      fontSize: 10.5,
      lineHeight: 1.5,
      marginLR: 14,
      marginTB: 18,
      entrySpacing: 8,
      sectionSpacing: 16,
      headingStyle: 'underline',
      headingCapitalization: 'uppercase',
      headingSize: 'm',
      nameSize: 'l',
      nameBold: true,
      titleSize: 'm',
      titleStyle: 'normal',
      titlePosition: 'below',
      personalAlign: 'left',
      personalArrangement: 'default',
      personalIconShow: true,
      personalBulletShow: false,
      personalBarShow: false,
      personalIconStyle: 'default',
      photoShow: false,
      photoGrayscale: false,
      photoSize: 'm',
      photoShape: 'circle',
      skillsStyle: 'grid',
      skillsColumns: 1,
      languagesStyle: 'grid',
      languagesColumns: 1,
      interestsStyle: 'grid',
      interestsColumns: 1,
      certificationsStyle: 'grid',
      certificationsColumns: 1,
      showSummaryHeading: true,
      showPageNumbers: true,
      showEmailInFooter: false,
      showNameInFooter: true,
      linkUnderline: true,
      linkBlueColor: false,
      linkIcon: false,
      entryLayout: 'default',
      entryTitleSize: 'm',
      entrySubtitleStyle: 'normal',
      entrySubtitlePlacement: 'next-line',
      descriptionIndent: false,
      listStyle: 'dash',
      educationOrder: 'school-degree',
      workOrder: 'employer-title',
      workGroupPromotions: false,
      accentType: 'basic',
      applyAccentTo: ['headings', 'headingLine'],
    },
  },
  {
    id: 'tech-green',
    name: 'Tech Green',
    description: 'Modern green theme for tech professionals',
    preview: {
      primaryColor: '#059669',
      secondaryColor: '#ecfdf5',
      accentColor: '#047857',
      fontFamily: 'JetBrains Mono',
      layout: 'single',
      backgroundColor: '#ffffff',
      textColor: '#1f2937',
    },
    design: {
      fontSize: 10,
      lineHeight: 1.5,
      marginLR: 14,
      marginTB: 16,
      entrySpacing: 6,
      sectionSpacing: 14,
      headingStyle: 'underline',
      headingCapitalization: 'uppercase',
      headingSize: 'm',
      nameSize: 'l',
      nameBold: true,
      titleSize: 's',
      titleStyle: 'normal',
      titlePosition: 'below',
      personalAlign: 'center',
      personalArrangement: 'horizontal',
      personalIconShow: true,
      personalBulletShow: false,
      personalBarShow: false,
      personalIconStyle: 'icon-only',
      photoShow: false,
      photoGrayscale: false,
      photoSize: 'm',
      photoShape: 'rounded',
      skillsStyle: 'list',
      skillsColumns: 2,
      languagesStyle: 'compact',
      languagesColumns: 3,
      interestsStyle: 'grid',
      interestsColumns: 3,
      certificationsStyle: 'list',
      certificationsColumns: 1,
      showSummaryHeading: true,
      showPageNumbers: true,
      showEmailInFooter: false,
      showNameInFooter: false,
      linkUnderline: true,
      linkBlueColor: true,
      linkIcon: true,
      entryLayout: 'default',
      entryTitleSize: 'm',
      entrySubtitleStyle: 'normal',
      entrySubtitlePlacement: 'next-line',
      descriptionIndent: false,
      listStyle: 'bullet',
      educationOrder: 'degree-school',
      workOrder: 'title-employer',
      workGroupPromotions: false,
      accentType: 'basic',
      applyAccentTo: ['headings', 'headingLine'],
    },
  },
  {
    id: 'classic-maroon',
    name: 'Classic Maroon',
    description: 'Traditional maroon design for conservative industries',
    preview: {
      primaryColor: '#881337',
      secondaryColor: '#fff1f2',
      accentColor: '#9f1239',
      fontFamily: 'Georgia',
      layout: 'sidebar-left',
      backgroundColor: '#ffffff',
      textColor: '#1f2937',
    },
    design: {
      fontSize: 10.5,
      lineHeight: 1.45,
      marginLR: 12,
      marginTB: 16,
      entrySpacing: 8,
      sectionSpacing: 16,
      headingStyle: 'underline',
      headingCapitalization: 'uppercase',
      headingSize: 'm',
      nameSize: 'm',
      nameBold: true,
      titleSize: 'm',
      titleStyle: 'normal',
      titlePosition: 'below',
      personalAlign: 'left',
      personalArrangement: 'default',
      personalIconShow: true,
      personalBulletShow: false,
      personalBarShow: false,
      personalIconStyle: 'default',
      photoShow: false,
      photoGrayscale: false,
      photoSize: 'm',
      photoShape: 'circle',
      skillsStyle: 'grid',
      skillsColumns: 1,
      languagesStyle: 'grid',
      languagesColumns: 1,
      interestsStyle: 'grid',
      interestsColumns: 1,
      certificationsStyle: 'grid',
      certificationsColumns: 1,
      showSummaryHeading: true,
      showPageNumbers: true,
      showEmailInFooter: false,
      showNameInFooter: false,
      linkUnderline: true,
      linkBlueColor: false,
      linkIcon: false,
      entryLayout: 'default',
      entryTitleSize: 'm',
      entrySubtitleStyle: 'normal',
      entrySubtitlePlacement: 'next-line',
      descriptionIndent: false,
      listStyle: 'bullet',
      educationOrder: 'degree-school',
      workOrder: 'title-employer',
      workGroupPromotions: false,
      accentType: 'basic',
      applyAccentTo: ['headings', 'headingLine'],
    },
  },
];

export function getDesignTemplate(id: string): DesignTemplate | undefined {
  return DESIGN_TEMPLATES.find(t => t.id === id);
}

export function getDesignTemplateByLayout(layout: string): DesignTemplate[] {
  return DESIGN_TEMPLATES.filter(t => t.preview.layout === layout);
}

export function applyDesignTemplate(template: DesignTemplate, customOverrides?: Partial<DesignTemplate['design']>): DesignTemplate['design'] {
  return {
    ...template.design,
    ...customOverrides,
  };
}
