import type { ThemeDefinition, ThemeId } from '@/types/resume-builder.types';

export const themeRegistry: Record<ThemeId, ThemeDefinition> = {
  default: {
    id: 'default',
    name: 'Default',
    colors: {
      primary: '#2563eb',
      secondary: '#4f46e5',
      accent: '#06b6d4',
      text: '#111827',
      textMuted: '#4b5563',
      background: '#ffffff',
      surface: '#f8fafc',
      border: '#e5e7eb',
    },
    fonts: {
      body: 'Inter, sans-serif',
      heading: 'Inter, sans-serif',
    },
    typography: { h1: 16, h2: 14, h3: 12, body: 10, small: 9, lineHeight: 1.5, letterSpacing: 0.1 },
    spacing: { sectionGap: 12, blockGap: 6, pagePaddingX: 20, pagePaddingY: 20 },
    radius: { sm: 4, md: 8, lg: 12 },
    shadows: { sm: 'none', md: '0 1px 3px rgba(0,0,0,0.12)', lg: '0 8px 20px rgba(0,0,0,0.12)' },
    borders: { width: 1, style: 'solid' },
  },
  midnight: {
    id: 'midnight',
    name: 'Midnight',
    colors: {
      primary: '#93c5fd',
      secondary: '#a78bfa',
      accent: '#67e8f9',
      text: '#e5e7eb',
      textMuted: '#cbd5e1',
      background: '#0f172a',
      surface: '#1e293b',
      border: '#334155',
    },
    fonts: { body: 'Inter, sans-serif', heading: 'Inter, sans-serif' },
    typography: { h1: 16, h2: 14, h3: 12, body: 10, small: 9, lineHeight: 1.6, letterSpacing: 0.2 },
    spacing: { sectionGap: 12, blockGap: 6, pagePaddingX: 20, pagePaddingY: 20 },
    radius: { sm: 4, md: 8, lg: 12 },
    shadows: { sm: 'none', md: 'none', lg: 'none' },
    borders: { width: 1, style: 'solid' },
  },
  executive: {
    id: 'executive',
    name: 'Executive',
    colors: {
      primary: '#0f172a',
      secondary: '#334155',
      accent: '#b45309',
      text: '#111827',
      textMuted: '#374151',
      background: '#ffffff',
      surface: '#f8fafc',
      border: '#d1d5db',
    },
    fonts: { body: '"Source Sans 3", sans-serif', heading: '"Merriweather", serif' },
    typography: { h1: 16, h2: 14, h3: 12, body: 10, small: 9, lineHeight: 1.55, letterSpacing: 0.2 },
    spacing: { sectionGap: 12, blockGap: 6, pagePaddingX: 20, pagePaddingY: 20 },
    radius: { sm: 2, md: 4, lg: 8 },
    shadows: { sm: 'none', md: 'none', lg: 'none' },
    borders: { width: 1, style: 'solid' },
  },
  creative: {
    id: 'creative',
    name: 'Creative',
    colors: {
      primary: '#7c3aed',
      secondary: '#ec4899',
      accent: '#f59e0b',
      text: '#111827',
      textMuted: '#4b5563',
      background: '#ffffff',
      surface: '#faf5ff',
      border: '#e9d5ff',
    },
    fonts: { body: 'Inter, sans-serif', heading: '"Space Grotesk", sans-serif' },
    typography: { h1: 16, h2: 14, h3: 12, body: 10, small: 9, lineHeight: 1.55, letterSpacing: 0.1 },
    spacing: { sectionGap: 12, blockGap: 6, pagePaddingX: 20, pagePaddingY: 20 },
    radius: { sm: 8, md: 12, lg: 18 },
    shadows: { sm: 'none', md: '0 1px 2px rgba(124,58,237,0.2)', lg: '0 8px 24px rgba(124,58,237,0.2)' },
    borders: { width: 1, style: 'solid' },
  },
  ats: {
    id: 'ats',
    name: 'ATS',
    colors: {
      primary: '#111827',
      secondary: '#1f2937',
      accent: '#111827',
      text: '#111827',
      textMuted: '#374151',
      background: '#ffffff',
      surface: '#ffffff',
      border: '#e5e7eb',
    },
    fonts: { body: 'Arial, sans-serif', heading: 'Arial, sans-serif' },
    typography: { h1: 16, h2: 14, h3: 12, body: 10, small: 9, lineHeight: 1.4, letterSpacing: 0 },
    spacing: { sectionGap: 12, blockGap: 6, pagePaddingX: 16, pagePaddingY: 16 },
    radius: { sm: 0, md: 0, lg: 0 },
    shadows: { sm: 'none', md: 'none', lg: 'none' },
    borders: { width: 1, style: 'solid' },
  },
};

export const getThemeById = (themeId: ThemeId): ThemeDefinition => themeRegistry[themeId] || themeRegistry.default;
